### ISSUE TITLE
Improved image layout on character descriptions

### ISSUE THREAD

**Issue by cavediverchris** [cavediverchris/Final-Fantasy-7-Walkthrough#1]
In the [characters section ](https://github.com/cavediverchris/Final-Fantasy-7-Walkthrough/blob/main/docs/introduction.md#characters )of the introduction, I would like the character images to be right-aligned so that the text wraps around it. I have this working well when previewed of the markdown, but not when the page has been generated into HTML.

**Comment by kimgarcellano** [comment]
Hi, I'm new to open source contribution and would like to help with this.

**Comment by cavediverchris** [comment]
> Hi, I'm new to open source contribution and would like to help with this.

Hello Kim! Thank you very much for your offer of helping, I'd really like your help! So I started writing a guide for Final Fantasy 7 when I was very young and I thought I would also learn how to build a webpage for it too, so I'm copy-pasting what I've written into GitHub at the moment.

With this issue in the characters section, I thought that it would look better with the images onthe right of the page, so I was using a little bit of HTML code using img src="address_to_the_image.jpg" , this would work well in the Markdown preview, but when the webpage gets compiled the images don't work and I'm not sure how the "address" should look in order to make the images appear properly..

The way GitHub works is that you create a branch (this is your own personal work area) ... then you make the changes to the file(s) that you need to change (introduction.md in this case) ... then once you think its all working and you are done, you then create a pull request which is the process of merging your work in with the main piece of work.

**Comment by cavediverchris** [comment]
Oh I just saw that you've already done all of that and you've made a pull request - I'll have a look now, thanks again!

**Comment by cavediverchris** [comment]
@kimgarcellano - thank you very much for making the changes, the images are now properly embedded! Thank you so much!

**Comment by kimgarcellano** [comment]
Hi @cavediverchris - Thanks for all your help and guidance. Cheers!
